### ISSUE TITLE
Upgrade fails due to templating issue "unexpected keyword argument 'indentfirst'"

### ISSUE THREAD

**Issue by simonpahl** [ansible/tower-operator#1032]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Apparently the jinja templating was upgraded from 2.11.3 to 3.1.1 and the current templates are no longer compatible.

### AWX Operator version

0.27.0

### AWX version

21.1.4

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

k3s

### Modifications

no

### Steps to reproduce

Just Upgrade from 0.26.0 to 0.27.0

### Expected results

Successfull upgrade 

### Actual results

Operator fails with `{{ extra_volumes | indent(width=8, indentfirst=True) }}\n{% endif %}\n): do_indent() got an unexpected keyword argument 'indentfirst'"}`

### Additional information

I rolled back to 0.26.0 and it worked again.

**Comment by whitej6** [comment]
I am experiencing the same issue. Looks to be from the change of the base image going to Jinja 3 
![image](https://user-images.githubusercontent.com/26559188/186509059-736d2926-a4f5-4672-a7ea-149f49ed91b4.png)

**Comment by whitej6** [comment]
https://github.com/pallets/jinja/blob/main/src/jinja2/filters.py#L800
This appears to be the offending issue.

**Comment by whitej6** [comment]
Appears to be caused by #1001

**Comment by whitej6** [comment]
@shanemcd will there be a new release cut with this fix?
